/**
 * Help command implementation with complete CLI spec documentation
 */

import { getSupportedProviders } from '../providers/index.js';

export function printHelpText(): void {
  // Get current list of supported providers dynamically
  const providers = getSupportedProviders();
  const providerList = providers.join('|');

  console.log('CIA - Vendor-neutral AI agent CLI tool for CI/CD pipelines');
  console.log('');
  console.log('USAGE:');
  console.log('  cia <command> [options]');
  console.log('  cia run <prompt> [options]');
  console.log('  cia models [options]');
  console.log('');
  console.log('COMMANDS:');
  console.log('  run <prompt>         Execute AI prompt with specified provider');
  console.log('  models               List available models (phase-1 scaffold output)');
  console.log('  mcp                  Manage Model Context Protocol servers');
  console.log('  skills               Manage and use skills for enhanced AI capabilities');
  console.log('');
  console.log('OPTIONS:');
  console.log('  -h, --help           Show this help message');
  console.log('  -v, --version        Show version information');
  console.log('');
  console.log('CORE OPTIONS:');
  console.log('  -p, --provider       AI provider (' + providerList + ') [default: codex]');
  console.log('  -m, --model          Model name (optional)');
  console.log('  --mode               Execution mode (lazy|strict) [default: lazy]');
  console.log('  --format             Output format (default|json) [default: default]');
  console.log('  --skill              Load and use a specific skill by name');
  console.log('');
  console.log('INPUT/OUTPUT:');
  console.log('  --input-file         Read prompt from file instead of command line');
  console.log('  --output-file        Write result to file [default: result.json]');
  console.log('  --output-format      Output format (json|yaml|md|text)');
  console.log('  --context            Add context files/URLs (multiple allowed)');
  console.log('');
  console.log('TEMPLATING:');
  console.log('  --template-file      Template file with {{variable}} placeholders');
  console.log('  --template-vars      Inline JSON variables for template substitution');
  console.log('  --template-vars-file JSON file containing template variables');
  console.log('');
  console.log('SCHEMA VALIDATION:');
  console.log('  --schema-file        JSON schema file for output validation');
  console.log('  --schema-inline      Inline JSON schema for output validation');
  console.log('  Note: strict mode requires either --schema-file or --schema-inline');
  console.log('');
  console.log('RELIABILITY:');
  console.log('  --retries            Number of retry attempts [default: 1]');
  console.log('  --retry-backoff      Enable exponential backoff on retries [default: true]');
  console.log('  --retry-timeout      Retry budget in milliseconds [default: 30000]');
  console.log('  --timeout            Timeout in seconds [default: 60]');
  console.log('  run guardrails       Includes stall detection and 1MB assistant output cap');
  console.log('');
  console.log('PROVIDER CONFIGURATION:');
  console.log('  --endpoint           Custom API endpoint URL');
  console.log('  --api-key            API key (prefer .cia/config.json provider options)');
  console.log('  Codex auth file:     ~/.codex/auth.json');
  console.log('  Claude auth:         `claude /login` or explicit provider config');
  console.log('');
  console.log('DEBUGGING:');
  console.log('  --log-level          Log level (DEBUG|INFO|WARN|ERROR) [default: INFO]');
  console.log('');
  console.log('ENTERPRISE NETWORKING:');
  console.log('  HTTP_PROXY           Proxy for outbound HTTP requests');
  console.log('  HTTPS_PROXY          Proxy for outbound HTTPS requests');
  console.log('  NO_PROXY             Comma-separated hosts that bypass proxy');
  console.log('  NODE_EXTRA_CA_CERTS  Path to custom corporate CA bundle (PEM)');
  console.log('  NODE_USE_ENV_PROXY   Force Node env proxy behavior (1|0)');
  console.log('  Tip: use --log-level DEBUG for transport diagnostics');
  console.log('');
  console.log('EXAMPLES:');
  console.log('  # Basic usage with Codex');
  console.log('  cia run "Explain how CI/CD works" --provider codex');
  console.log('');
  console.log('  # Strict mode with schema validation');
  console.log('  cia run "Generate user JSON" --mode strict --schema-file user.schema.json');
  console.log('');
  console.log('  # Read from file with specific output format');
  console.log('  cia run --input-file prompt.txt --output-format yaml --output-file result.yaml');
  console.log('');
  console.log('  # Multiple context sources');
  console.log('  cia run "Summarize these docs" --context docs/api.md --context docs/guide.md');
  console.log('');
  console.log('  # Template with variables');
  console.log('  cia run --template-file deploy.template --template-vars-file vars.json');
  console.log('');
  console.log('  # Codex provider');
  console.log('  cia run "Hello world" --provider codex');
  console.log('');
  console.log('  # Claude provider');
  console.log('  cia run "Hello world" --provider claude');
  console.log('');
  console.log('  # Use a skill');
  console.log('  cia run "Debug this code" --skill debugging-expert');
  console.log('');
  console.log('  # List available skills');
  console.log('  cia skills list');
  console.log('');
  console.log('CONFIGURATION:');
  console.log('  Configuration is loaded in this order (later overrides earlier):');
  console.log('  1. User config: ~/.cia/config.json');
  console.log('  2. Repository config: .cia/config.json');
  console.log('  3. Command line arguments');
  console.log('');
  console.log('  Environment file (~/.cia/.env) is used for ${ENV_VAR} substitution only.');
  console.log('');
  console.log('EXIT CODES:');
  console.log('  0  Success');
  console.log('  1  Input validation error');
  console.log('  2  Schema validation error');
  console.log('  3  Authentication/configuration error');
  console.log('  4  LLM execution error');
  console.log('  5  Timeout error');
  console.log('');
  console.log('For more information, visit: https://github.com/ciagent/ciagent');
}
