/**
 * Help command implementation with complete CLI spec documentation
 */

export function printHelpText(): void {
  console.log('CIA - Vendor-neutral AI agent CLI tool for CI/CD pipelines');
  console.log('');
  console.log('USAGE:');
  console.log('  cia <command> [options]');
  console.log('  cia run <prompt> [options]');
  console.log('');
  console.log('COMMANDS:');
  console.log('  run <prompt>         Execute AI prompt with specified provider');
  console.log('');
  console.log('OPTIONS:');
  console.log('  -h, --help           Show this help message');
  console.log('  -v, --version        Show version information');
  console.log('');
  console.log('CORE OPTIONS:');
  console.log('  -p, --provider       AI provider (azure|openai|anthropic|google|local) [default: azure]');
  console.log('  -m, --model          Model name (e.g., gpt-4, claude-3-sonnet)');
  console.log('  --mode               Execution mode (lazy|strict) [default: lazy]');
  console.log('  --format             Output format (default|json) [default: default]');
  console.log('');
  console.log('INPUT/OUTPUT:');
  console.log('  --input-file         Read prompt from file instead of command line');
  console.log('  --output-file        Write result to file [default: result.json]');
  console.log('  --output-format      Output format (json|yaml|md|text)');
  console.log('  --context            Add context files/URLs (multiple allowed)');
  console.log('');
  console.log('SCHEMA VALIDATION:');
  console.log('  --schema-file        JSON schema file for output validation');
  console.log('  --schema-inline      Inline JSON schema for output validation');
  console.log('  Note: strict mode requires either --schema-file or --schema-inline');
  console.log('');
  console.log('RELIABILITY:');
  console.log('  --retries            Number of retry attempts [default: 1]');
  console.log('  --retry-backoff      Enable exponential backoff on retries [default: true]');
  console.log('  --timeout            Timeout in seconds [default: 60]');
  console.log('');
  console.log('PROVIDER CONFIGURATION:');
  console.log('  --endpoint           Custom API endpoint URL');
  console.log('  --api-key            API key (prefer environment variables)');
  console.log('  --api-version        API version for Azure/OpenAI');
  console.log('  --org                Organization ID for OpenAI');
  console.log('');
  console.log('DEBUGGING:');
  console.log('  --log-level          Log level (DEBUG|INFO|WARN|ERROR) [default: INFO]');
  console.log('');
  console.log('EXAMPLES:');
  console.log('  # Basic usage with Azure OpenAI');
  console.log('  cia run "Explain how CI/CD works" --model gpt-4');
  console.log('');
  console.log('  # Strict mode with schema validation');
  console.log('  cia run "Generate user JSON" --mode strict --schema-file user.schema.json');
  console.log('');
  console.log('  # Read from file with specific output format');
  console.log('  cia run --input-file prompt.txt --output-format yaml --output-file result.yaml');
  console.log('');
  console.log('  # Multiple context sources');
  console.log('  cia run "Summarize these docs" --context docs/api.md --context docs/guide.md');
  console.log('');
  console.log('  # Alternative provider');
  console.log('  cia run "Hello world" --provider openai --model gpt-3.5-turbo');
  console.log('');
  console.log('CONFIGURATION:');
  console.log('  Configuration is loaded in this order (later overrides earlier):');
  console.log('  1. Environment variables (CIA_PROVIDER, CIA_MODEL, etc.)');
  console.log('  2. User config: ~/.cia/config.json');
  console.log('  3. Repository config: .cia/config.json');
  console.log('  4. Command line arguments');
  console.log('');
  console.log('  Environment file: ~/.cia/.env');
  console.log('');
  console.log('EXIT CODES:');
  console.log('  0  Success');
  console.log('  1  Input validation error');
  console.log('  2  Schema validation error');
  console.log('  3  Authentication/configuration error');
  console.log('  4  LLM execution error');
  console.log('  5  Timeout error');
  console.log('');
  console.log('For more information, visit: https://github.com/ciagent/ciagent');
}